name: TheMix
main: VectorNetworkProject\TheMix\TheMix
api: 3.0.0
softdepend:
- ScoreboardsPE

description: "Original game of VectorNetwork"
website: "https://vector-network.tk"
version: 0.0.9-BETA
authors:
- InkoHX
- MazaiCrafty
- yuko fuyutsuki
- DusKong
- UramnOIL
