<?php


namespace VectorNetworkProject\TheMix;


use pocketmine\plugin\PluginBase;

class TheMix extends PluginBase
{
    public function onLoad()
    {
        parent::onLoad(); // TODO: Change the autogenerated stub
    }

    public function onEnable()
    {
        parent::onEnable(); // TODO: Change the autogenerated stub
    }

    public function onDisable()
    {
        parent::onDisable(); // TODO: Change the autogenerated stub
    }
}
